### ISSUE TITLE
Altre risorse 

### ISSUE THREAD

**Issue by gentilinigm** [csunibo/laboratorio-sicurezza-informatica#2]
Segnalo la presenza di altre risorse che potrebbero essere utili [qui](https://tkanon.ninja/Uni/OLD/LAUREA_INGEGNERIA_INFORMATICA/3/AMMINISTRAZIONE_DI_SISTEMI_E_SICUREZZA_INFORMATICA_T_C.I._-_LABORATORIO_DI_SICUREZZA_INFORMATICA_T/)

Non so chi è l'autore

**Comment by foxyseta** [comment]
Grazie davvero mille! Essendo anonimo spero non si offenda se non lo citiamo🙈 Forse potrebbero dare un occhio a questo link i ragazzi che stann frequentando sicurezza?

**Comment by foxyseta** [comment]
Grazie davvero mille! Essendo anonimo spero non si offenda se non lo citiamo🙈 Forse potrebbero dare un occhio a questo link i ragazzi che stanno frequentando il lab di sicurezza? Per esempio @crestaa @takenX10 e @kocierik @specialfish9 ma anche gli altri. Possono aprire una PR in cui aggiungono questi materiali.
